package models

import (
	uuid "github.com/google/uuid"
)

/*
Works just like gorm.Model, but we have control over this one.

Must be exported from this package (so use Model instead of model), or else GORM doesn't make the child models inherit the columns defined here.

We don't want the UINT ID field because if you try to insert into the database after copying it with jinzhu.copier, GORM will attempt to insert it with a UINT for the ID and not recognize the UUID.
*/
type Base struct {
	ModelWithUUID
	ModelWithTimestamps
}

type ModelWithUUID struct {
	// gen_random_uuid() only works in Postgres v14+. If you use an older version, you must change how the UUID is generated by using an extension.
	ID uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
}

type ModelWithTimestamps struct {
	CreatedAt uint64 `gorm:"autoCreateTime;not null"`
	UpdatedAt uint64 `gorm:"autoUpdateTime;not null"`
	DeletedAt uint64 `gorm:"index"`
}
