// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountResponse struct {
	Token    string `json:"token,omitempty" `
	Redirect string `json:"redirect,omitempty" `
}

type Login struct {
	Email    string `json:"email" `
	Password string `json:"password" `
}

type Register struct {
	FirstName string `json:"firstName" `
	LastName  string `json:"lastName" `
	Email     string `json:"email" `
	Password  string `json:"password" `
}

type User struct {
	FirstName string `json:"firstName" `
	LastName  string `json:"lastName" `
	Email     string `json:"email" `
}
