// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"com.vitanexus/main/internal/orm/models"
)

type NewTodo struct {
	models.Base
	Text   string `json:"text" `
	UserID string `json:"userId" `
}

type Todo struct {
	models.Base
	ID   string `json:"id" `
	Text string `json:"text" `
	Done bool   `json:"done" `
	User *User  `json:"user" `
}

type UpdateTodo struct {
	models.Base
	Text   string `json:"text" `
	UserID string `json:"userId" `
}

type User struct {
	models.Base
	FirstName string `json:"firstName" gorm:"column:first_name"`
	LastName  string `json:"lastName" gorm:"column:last_name"`
	Email     string `json:"email" gorm:"not null"`
	Password  string `json:"password" gorm:"not null"`
}
