// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"com.project001/main/internal/orm/models"
)

type Login struct {
	models.Base
	Email    string `json:"email" `
	Password string `json:"password" `
}

type NewUser struct {
	models.Base
	FirstName string `json:"firstName" `
	LastName  string `json:"lastName" `
	Email     string `json:"email" `
	Password  string `json:"password" `
}

type Register struct {
	models.Base
	FirstName string `json:"firstName" `
	LastName  string `json:"lastName" `
	Email     string `json:"email" `
	Password  string `json:"password" `
}

type UpdateUser struct {
	models.Base
	FirstName string `json:"firstName" `
}

type User struct {
	models.Base
	FirstName string `json:"firstName" gorm:"column:first_name"`
	LastName  string `json:"lastName" gorm:"column:last_name"`
	Email     string `json:"email" gorm:"not null"`
	Password  string `json:"password" gorm:"not null"`
}
